### ISSUE TITLE
As a commercial GRC tool author, I would like a defined set of validation rules that are portable and machine-readable so that I can build software that automatically updates the rules based on the update cycle of governing bodies like NIST, FedRAMP, and DISA

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#1]
As a security and risk tool developer, I want a portable, automatable ruleset I can incorporate to provide validation of the SSP while I am authoring it.

**Comment by mike-stern** [comment]
related to #10

**Comment by ohsh6o** [comment]
Convert this to a label for epics or something, as the issue epics do not seem to be working.
