### ISSUE TITLE
One-Pager Summary

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#110]
**Extended Description**
As a FedRAMP reviewer, in order to have a quick summary of all the findings before looking at each validation error and all the details it provides.

**Preconditions**
- A rules count after a validation pass is complete (18F/fedramp-automation#109)
- Determine a method for talking about rule completeness.

**Acceptance Criteria**
- [x] A collection of validation warnings and errors [categorized into sections like the current report checklist](https://github.com/18F/fedramp-automation/blob/1bf5eff498afc133977c83d465cc93fe7a8987a4/resources/validations/README.md#authors-and-reviewers-what-validations-are-currently-implemented)
- [x] A breakdown of validation warnings and errors by severity within the categorized sections of the report

**Story Tasks**
- [x] SPIKE: Determine if grouping by report sections is viable.
- [ ] Review groupings with team
- [ ] Review the Draft OSCAL SSP Document to estimate the remaining tasks of writing validation rules.
- [x] Get Rudder's feedback/recommendations on summarizing large amounts of data

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [x] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] ~Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing~
 - [x] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [x] Source code merged - Code that’s demoed must be in source control and merged
 - [x] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] ~Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling?~
 - [ ] ~Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)~
 - [ ] ~Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)~
 - [x] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [x] Code refactored for clarity - Code must be clean, self-documenting
 - [x] No local design debt
 - [ ] ~Load/performance tests passed - test data needed - saxon instrumentation~
 - [ ] ~Documentation generated - update readme or contributing markdown as necessary.~
 - [ ] ~Architectural Decision Record completed as necessary for significant design choices~

**Comment by danielnaab** [comment]
We didn't complete a review of rules in the categorization, and opted to wait for feedback from the current user session instead.
