### ISSUE TITLE
Running Schematron Validation in Github Action Broken

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#142]
# Describe the bug

It appears the Github Action for [interactively running the Schematron pipeline from Github](https://github.com/18F/fedramp-automation/blob/dd576c7541c1c924890c27f15d5595aef469622f/.github/workflows/runSchematronValidation.yml#L22-L33) has issues with how the `git submodule` checkout occurs. This seems different from [the other Action FR/10x ASAP devs wrote prior](https://github.com/18F/fedramp-automation/blob/dd576c7541c1c924890c27f15d5595aef469622f/.github/workflows/xspecRunner.yml#L15-L21) and I think that might be part of the issue, but we need to also make sure this works.

# Who is the bug affecting?

Developers who want to use this to demo.

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?

Interactively running the Schematron pipeline from Github Actions.

# When does this occur?

Consistently, see [this Action's pipeline history for examples](https://github.com/18F/fedramp-automation/actions/workflows/runSchematronValidation.yml).

# How do we replicate the issue?

1. Select the [relevant Action](https://github.com/18F/fedramp-automation/actions/workflows/runSchematronValidation.yml)
1. Set the source Schematron file as `src/validations/rules/ssp.sch`.
1. Set the SSP file as `src/validations/test/demo/FedRAMP-SSP-OSCAL-Template.xml`
1. Observe error.

<img width="1437" alt="Screen Shot 2021-07-22 at 11 07 14 AM" src="https://user-images.githubusercontent.com/61464190/126662530-e4b40da9-f33d-4c5e-8920-12e4ecc61dd1.png">

# Expected behavior (i.e. solution)

Validations processing completes without issue.

**Comment by danielnaab** [comment]
Closing since we can validate via the UI.
