### ISSUE TITLE
Show all OSCAL document rules in web documentation

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#152]
**Extended Description**

Support each OSCAL document type in the web documentation.

Follow-on work: So we can validate all OSCAL document types in a FedRAMP authorization package submission, determine how such a package should be structured.

Related: [https://github.com/18F/fedramp-automation/blob/develop/src/validations/docs/adr/0009-multi-document-rules.md](https://github.com/18F/fedramp-automation/blob/develop/src/validations/docs/adr/0009-multi-document-rules.md)

**Preconditions**
- [ ] Design work for this feature (18F/fedramp-automation#151)

**Acceptance Critera**
- Approach documented
- Follow-up tickets created

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - 
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by GaryGapinski** [comment]
Related: https://github.com/18F/fedramp-automation/blob/develop/src/validations/docs/adr/0009-multi-document-rules.md.

**Comment by danielnaab** [comment]
Created #513 and #514 as follow-up work.

**Comment by danielnaab** [comment]
Split the ZIP archive portion of this into a separate issue: #515
