### ISSUE TITLE
Minimally Defined Ports and Protocols

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#161]
**Extended Description**
- As a FedRAMP reviewer, in order to sanity check SSP submissions, I want ensure that CSOs minimally include protocols expected in contemporary implementations.
- Refer to _[Guide to OSCAL-based FedRAMP System Security Plans](https://github.com/18F/fedramp-automation/blob/develop/documents/Guide_to_OSCAL-based_FedRAMP_System_Security_Plans_(SSP).pdf)_ §4.25.

**Acceptance Criteria**
- A validation that asserts the declaration of minimal (typical) protocols.

**Story Tasks**
- Create one or more Schematron assertions which ensure a minimal set of protocols is defined within an SSP.

**Definition of Done**
 - [x] Acceptance criteria met
 - [x] Unit test coverage of our code > 95%  
 - [x] Automated code quality checks passed 
 - [ ] ~~Security reviewed and reported (Wes to be consulted on this)~~
 - [x] Reviewed against plain language guidelines
 - [x] Code must be self-documenting
 - [x] No local tech debt
 - [x] Load/performance tests passed – needs to be created/automated
 - [x] Documentation updated
 - [ ] ~~Architectural Decision Record completed as necessary for significant design choices~~
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by markXLIX** [comment]
Define 'minimal (typical) protocols.
