### ISSUE TITLE
Improve Search Box Suggestion Text

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#170]
**Extended Description**

As a FedRAMP reviewer, I would like an explanation of what I can search (or how) in order to know what the search box does.

**Acceptance Criteria**
- [x] Inline documentation (nothing lengthy, hover or tooltip) that explains above, inside, or near the search box what it can search from the validation and how to use it (can I only type text or can I add filter keywords? I know it can't but the reviewers do not)

**Story Tasks**
- [x] Review design approach with Scott
- [x] Implement code enhancements

**Definition of Done** - WITH UI
 - [x] Acceptance criteria met
 - [x] Unit test coverage of our code > 90% - needs automation story
 - [ ] ~Accessibility tests pass - needs automation story~
 - [x] Automated code quality checks pass
 - [ ] ~Security reviewed and reported - check in with Wes on what we could do here~
 - [x] Reviewed against plain language guidelines
 - [ ] ~Design QA passed~
 - [x] Code must be self-documenting
 - [x] No local tech debt
 - [ ] ~Documentation updated~
 - [ ] ~Architectural Decision Record completed as necessary for significant design choices~
 - [x] PR reviewed & approved
 - [x] Source code merged

**Comment by ohsh6o** [comment]
Per refinement how results are grouped and the nature of the search results are tricky. Damn will modify word text in sprint. Consider rescoping this for search improvements.

**Comment by sreuber** [comment]
@danielnaab For the time being, I recommend "Filter results appear as you type, showing exact matches." I don't have much insight as to where the disconnect is, but from what I've heard it is that the actual behavior of the interaction is misunderstood, so I'm addressing that the results appear as the user types & also specifying the matches are exact. Results should appear in text underneath the heading, not as placeholder text in the input. 

Sample below.
<img width="374" alt="Screen Shot 2022-02-18 at 3 12 53 PM" src="https://user-images.githubusercontent.com/98423612/154762080-66ed1984-f717-4c06-b668-76bac7137184.png">
