### ISSUE TITLE
Update or Accept Risk of Overmind Dev Tools Vulnerabilities

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#175]
**Extended Description**

As a 10x ASAP developer, in order to maintain the security of the dependencies of our development tools, I would like to determine a best course of action for moderate impact vulnerabilities for the `electron` and `ws` packages from NPM.

<img width="1046" alt="Screen Shot 2021-07-28 at 2 37 17 AM" src="https://user-images.githubusercontent.com/61464190/127278842-ad421c4e-7bb6-4c29-a5a6-c7e6f9a3f519.png">

NOTE: Github has indicated through Dependabot for the last week it is not automatically patchable because it is a transitive dependency, so we can safely presume we're on our own.

**Acceptance Critera**
- One of the following:
- [ ] A documented explanation of the risk we can ask our project manager to accept.
- [x] Evidence of an updated patched version of this vulnerability.

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description

**Comment by danielnaab** [comment]
Dependencies are updated, vulnerabilities are all resolved.
