### ISSUE TITLE
Wire Frames for User Feedback Session #2

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#180]
**Extended Description**

The 10x ASAP Team will create preliminary wireframes for the main user interface with the intent of showing them to the FedRAMP FART team for review and feedback.  The wireframes will include

- All required on screen elements.
- Visual identification system for section and message identity.
- Contextual links to artifacts and reports for all messages.

**Preconditions**
- [ ] Plan approval and guidance from FedRAMP PMO
- [ ] Test data designed for use with the goals of this session: 18F/fedramp-automation#130

**Acceptance Criteria**
- [ ] Receive feedback around level-setting and basics (specifically terminology and layout).
- [ ] Work with PO to ensure all applicable work is added to backlog.

**Story Tasks**
- [ ] Design wireframes and create visual documentation.
.

**Definition of Done**
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by sstatz** [comment]
@rrkane10x Can you please update this story with what you intend to do?  Thanks!

**Comment by ohsh6o** [comment]
@rrkane10x we going to close this story out as discussed?

**Comment by rrkane10x** [comment]
Closing issues and taking UI pairing with Dan Naab for UX work.
