### ISSUE TITLE
Journey Maps

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#182]
**Extended Description**

The 10x ASAP Team will create a user interaction journey map as a visualization of the points where all users interact with the application in order accomplish a goal. The intent of creating the journey map is to give the FedRAMP FART team a visual point of reference for the application interaction points within the larger SSP review process.  The journey map will include:

- Each user who interacts with the application.
- Interaction scenarios to describe the user's goal or need and specific expectations from the interaction.
- Journey Phases showing the different high-level stages in the interaction  journey. 
- Opportunities are insights gained from the interaction mapping that speak to how the user experience can be optimized.
 
**Preconditions**
- [ ] Plan approval and guidance from FedRAMP PMO
- [ ] Test data designed for use with the goals of this session: 18F/fedramp-automation#130

**Acceptance Criteria**
- [ ] Receive feedback around level-setting and basics (specifically terminology and layout).
- [ ] Work with PO to ensure all applicable work is added to backlog.

**Story Tasks**
- [ ] Design wireframes and create visual documentation.
.

**Definition of Done**
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by sstatz** [comment]
@rrkane10x Can you also update this story with what you intend to do?  Thanks!

**Comment by ohsh6o** [comment]
I had a chance to review the journey map and this is ok for now. @sstatz can you make sure we close out this story next week? Thanks.
