### ISSUE TITLE
Change  Schematron report elements to assert elements where possible

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#188]
Tech Debt: Remove usage of the Schematron report element

**Extended Description**
- Description...

**Preconditions**
- None.

**Acceptance Critera**
- All usage of `<sch:report>` elements is informational

**Story Tasks**
- [x] Any validation, as opposed to informative, tests should be changed to `<sch:assert>` elements
- [x] All `<sch:report>` elements which remain in use should have a `test="true()"` and `role="information"`.

**Definition of Done**
Inapplicable items are ~~struck through~~.

 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [x] Code quality checks passed (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
~~- [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing~~
 - [x] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [x] Source code merged - Code that’s demoed must be in source control and merged
 - [x] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
~~- [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling?~~
~~- [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)~~
~~- [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)~~
~~- [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)~~
 - [x] Code refactored for clarity - Code must be clean, self-documenting
 - [x] No local design debt
 - [x] Load/performance tests passed - test data needed - saxon instrumentation
~~- [ ] Documentation generated - update readme or contributing markdown as necessary.~~
~~- [ ] Architectural Decision Record completed as necessary for significant design choices~~

**Comment by GaryGapinski** [comment]
This can be performed just about any time.

I may create an explanation of Schematron assertions and how they are created and employed.

**Comment by GaryGapinski** [comment]
Closed by #212.

**Comment by GaryGapinski** [comment]
Closed by #212.
