### ISSUE TITLE
Every Control has a Response in the appropriate place. Example: lettered parts

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#22]

**Comment by ohsh6o** [comment]
I guess I need to pause this one until tomorrow. I will need to get some feedback from Brian Ruf on [how an example would work](https://gitter.im/usnistgov-OSCAL/FedRAMP-10x-Schematron?at=5fceb2a84d68926e7f37c060).

**Comment by ohsh6o** [comment]
Pushed some upstream recommendations per conversation in Gitter today, but will fix our copy of the XML SSP in the ./test/demo subdirectory for now and move ahead.
