### ISSUE TITLE
User Feedback Mechanism

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#220]
**Extended Description**
- As a user of any persona, in order to improve the application, I want to be able to easily provide feedback to the development team within the application while it is top of mind.

**Acceptance Criteria**
- A user can be in the application and email feedback to the team. tts-10x-asap@gsa.gov

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - 
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by ohsh6o** [comment]
Something we should discuss, who is the "user" we mean in this context? We have a few personas, do we mean all of them?
