### ISSUE TITLE
Draft the Phase 4 Pitch

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#222]
**Extended Description**
- Prepare & present a pitch to the 10x PMO & Ashley Mahan for Phase 4 funding.

**Preconditions**
- We've made a decision to pitch for Phase 4 funding.
- We have a commitment from CMS to work alongside with us.
- We have a commitment from an outside vendor to work with us. 

**Acceptance Criteria**
- Each team member presents different pieces of the pitch deck.
- 

**Story Tasks**
- [x] Communicate the value proposition
- [x] Communicate the current problem
- [x] Share the planned approach
- [x] Communicate why this matters
- [x] Share the Phase 4 Proposal
- [x] Be ready for a Dry Run with 10x on 10/6

**Comment by sstatz** [comment]
Pitch Deck and Outline located in this folder. https://drive.google.com/drive/u/2/folders/1a_rzerPKQ-0KfEny5u-H8DKh4knwmf4y

**Comment by sstatz** [comment]
This is currently blocked as we need an agreement from an outside vendor to work with us.

**Comment by ohsh6o** [comment]
Per standup Monday, @jonadecker and @sstatz confirmed that a confirmed CSP endorsement for a CMS pilot is not a strict requirement in the eyes of the 10x PMO. We will continue working on this slides and prepare for a dry run pitch pushed back from this week to next week.
