### ISSUE TITLE
Review Interconnection Changes from Upstream

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#232]
Review https://github.com/GSA/fedramp-automation/pull/170 and update FedRAMP Schematron to match changes

**Comment by GaryGapinski** [comment]
Typo "Polciy" at line 446 in `fedramp_values.xml`.

**Comment by GaryGapinski** [comment]
`service-model` and `deployment-model` value-sets have dissonant bindings.

**Comment by GaryGapinski** [comment]
The changes to `fedramp_values.xml` do not appear to need any changes to `ssp.sch`.

**Comment by ohsh6o** [comment]
> `service-model` and `deployment-model` value-sets have dissonant bindings.

We can keep this as-is, per previous conversation.

**Comment by ohsh6o** [comment]
> Typo "Polciy" at line 446 in `fedramp_values.xml`.

I'll fix this sorry about that.

**Comment by ohsh6o** [comment]
I talked with Gary and I am happy to accept this review is complete.
