### ISSUE TITLE
Gauge CMS Stakeholders' Interest in Validation Rules and P4

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#238]
**Extended Description**

As a 10x ASAP developer, to understand the likelihood and level of effort for a federal agency to adopt our tooling, I would like to consult a willing agency to adopt our validations platform into their organization and integrate it in their own process.

We have been talking to CMS stakeholders in security assessment from Phase 2 about leveraging our rules. After our last meeting, we would like to gauge their level of interest for commitment to integrating more deeply in Phase 4.

Notes from Dan and others about important details to discuss with CMS (who, what when, where, why?):

https://docs.google.com/document/d/13GPFAzONRa-Q__ozDwV7SAu4o8wbg16GD2NKMHRJc4A/edit

**Preconditions**
- N/A

**Acceptance Criteria**
- [x] A brief summary in Google Drive summary of discussions with CMS and potential next steps.

**Story Tasks**
- [x] Meet up with CMS stakeholders to discuss:
  - [x] feedback after they tested the validations and prototype UI.
  - [ ] List out what Andres' partnership would look like in a Phase 4 and share with him.
  - [ ] Ask if he's be part of the pitch.

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Documentation generated - update readme or contributing markdown as necessary.

**Comment by ohsh6o** [comment]
Converted this to a story. Let's try and get feedback from Andres during the beginning of this sprint and adapt accordingly.

**Comment by danielnaab** [comment]
Meeting notes: https://docs.google.com/document/d/1zaJxj_wbXmR2rAhYLrz-h1Fsu0F0Iz9pIf5CIJ9uxfo/edit

**Comment by ohsh6o** [comment]
Meeting notes from yesterday's sync meeting with Andres.

https://docs.google.com/document/d/1KlDQonMjP8HiiwdRrbpo0PuZ9igIcqLg5wYQ6PSDWYo/edit

**Comment by ohsh6o** [comment]
@jonadecker and @ohsh6o will brief FR and 10x PMOs to get further guidance on clarification on next best steps for P4 pitch.

**Comment by ohsh6o** [comment]
We are continue working with CMS as a pre-condition to moving forward with a P4 of this project, per 18F#222 updates. We will continue a more focused effort on supporting CMS in discussing this project with vendors in 18F#273.
