### ISSUE TITLE
Analyze User Feedback from Session 3

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#239]
**Extended Description**

As the FedRAMP PMO, I would like the 10x ASAP team to use feedback from previous user testing to plan the next user feedback session and address updated validation development.

**Preconditions**
- [x] Wrap up review of previous session feedback in 18F#240.

**Acceptance Criteria**
- [x] A documented plan for the user feedback group session on September 1st.
- [x] A documented plan for subsequent 1-on-1 sessions.

**Story Tasks**
- [x] Meet with Melissa and the Volpe's to plan the next user feedback group session.
- [x] Draft reminder email for FART and JAB participants.
- [x] Schedule follow-up 1-on-1 sessions and include Melissa and Volpe developer team.

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [x] Usability testing and other user research methods must be conducted at regular intervals throughout the development 
 - [x] Documentation generated - update readme or contributing markdown as necessary.

**Comment by rrkane10x** [comment]
Completed 1:1 testing and produced a backlog of items collected from the user feedback sections. Reviewed the backlog with AJ.
