### ISSUE TITLE
Check Locations of Data Centers US Only

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#246]
**Extended Description**
- As a FedRAMP reviewer, in order to ensure the data centers with federal data are not outside the US, I want the system to check the country of the address of the primary and secondary data center locations.

**Preconditions**
N/A

**Acceptance Criteria**
- [x] Ensure `location` for `data-center` of `@class` `primary` is in United States.
- [x] Ensure `location` for `data-center` of `@class` `secondary` is in United States.

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [x] Code quality checks passed (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [x] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [x] Source code merged - Code that’s demoed must be in source control and merged
 - [x] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [x] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [x] Code refactored for clarity - Code must be clean, self-documenting
 - [x] No local design debt
 - [x] Load/performance tests passed - test data needed - saxon instrumentation
 - [x] Documentation generated - update readme or contributing markdown as necessary.
 - [x] Architectural Decision Record completed as necessary for significant design choices

**Comment by GaryGapinski** [comment]
ISO 3166 plus more at https://www.cia.gov/the-world-factbook/references/country-data-codes/.

**Comment by ohsh6o** [comment]
> This will require that the `<country>` element (ISO 3166-1 alpha-2 country code) be present. It is optional in the XML Schema, and the XML Schema does not constrain its content to ISO 3166-1 entries.
> 
> The `FedRAMP-SSP-OSCAL-Template.xml` document lacks `<country>` elements in its `<location>` elements.
> 
> The _Guide to OSCAL-based FedRAMP System Security Plans_ §4.23 does not indicate that `<country>` is required.

But it does seem that [NIST OSCAL support a country element right](https://pages.nist.gov/OSCAL/reference/develop/system-security-plan/xml-definitions/#/assembly/oscal-metadata/address/country). Do we only need the US code anyway? We just want it to show an error when it is not set to `US`, correct?

**Comment by ohsh6o** [comment]
On second thought, I think I have the requirement backwards, @GaryGapinski, so I think you are in fact correct and I am mistaken.

> Check that no piece in the inventory is in or holds data in China, or included. Especially look for data center locations and manufacturers.

This requirement, especially given [FAR 889(a)(1)(B)](https://www.federalregister.gov/documents/2020/07/14/2020-15293/federal-acquisition-regulation-prohibition-on-contracting-with-entities-using-certain) is much closer to what you said, and I should be less casual summarizing. To make it more adaptable and useful, perhaps we need to think about the country list after all.
