### ISSUE TITLE
Support CMS Pitches to Vendors

### ISSUE THREAD

**Issue by sstatz** [18F/fedramp-automation#273]
**Extended Description**

As a CMS agency stakeholder, to empower vendors with the necessary information and benefits of using the FedRAMP ASAP validations for a FedRAMP agency authorization sponsored by FedRAMP, I would like FedRAMP PMO and 10x to provide supporting materials for slide decks when I present to those vendors.

**Preconditions**
N/A

**Acceptance Criteria**
- [x] CMS has relevant and necessary information in slides from our team to support pitching collaboration with the ASAP team and vendor(s).

**Story Tasks**
- [X] Follow up with CMS stakeholder and ask what specific points he wants conveyed (approach, overview, technical depth, cost savings)
  - [x] Determine questions we have CMS FedRAMP team: current process, business rules, and automation/workflow for a FedRAMP review
- [x] Confirm with CMS relevant format: separately prepare a slide deck or actively collaborate on slide deck
- [x] Review and dry-run with CMS stakeholder before pitching with vendors.

**Comment by ohsh6o** [comment]
We are moving forward in planning meetings with CMS leadership (and potential stakeholders for this P4) on Friday. [Outline and notes are being tracked here](https://docs.google.com/document/d/13GPFAzONRa-Q__ozDwV7SAu4o8wbg16GD2NKMHRJc4A/edit) to plan for that meeting.

**Comment by ohsh6o** [comment]
The 10x ASAP Team and I performed our first pitch to an interested cloud service provider using [our slide deck for for a proposed CMS pilot with 10x and FedRAMP PMO support](https://docs.google.com/presentation/d/1pZnjSoou2ma3-TJ6YmHK01Ca3kxyhk2ioDIfSF6TMmY/edit#slide=id.gef959c8ad0_0_53). We will continue to make modifications, but initial impressions were favorable, albeit rushed.

We are in the process of scheduling another pitch with the same CSP, and CMS leadership is arranging another potential one two CSPs given the level of interest from the first.

**Comment by ohsh6o** [comment]
@sstatz I confirmed with @andres-gov material for the slide prep is good to go, we will just move forward with more pitches. Do we want to:

1. Keep this backlog item rolling sprint to sprint (if we have 1-2 more weeks of pitch meetings)?
2. Close it out in favor of a more focused story now that the material and leg work is complete?

If not via comments here, I guess we can discuss tomorrow during standup. :-)
