### ISSUE TITLE
Clearly distinguish message types

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#288]
**Extended Description**
As a user, I would like clarity on what different message types in the UI mean.

**Acceptance Criteria**
- [ ] A visual symbol to clarify positive messaging
- [ ] A visual symbol to clarify diagnostic messaging on what needs to be fixed
- [ ] Helper text that indicates if an individual message is positive or diagnostic when the user selects or hover over it
- [ ] Reconsider usage of severity background colors

**Story Tasks**
- [ ] Tasks...

**Definition of Done** - WITH UI
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by delnaweil** [comment]
superceded by other UI work
