### ISSUE TITLE
FedRAMP SSP Template Section 13 - annotate with sub-sections

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#295]
**Extended Description**
As a FedRAMP reviewer, in order to ensure I understand validations when organized by FedRAMP SSP templates, I would like to see in Section 13 the sub-sections which show which control families.

NOTE: This is our current interface as of [`3f3df69`](https://github.com/18F/fedramp-automation/commit/3f3df69e7c5bfc712e385c).

<img width="1483" alt="Screen Shot 2021-09-30 at 9 04 33 AM" src="https://user-images.githubusercontent.com/61464190/135460469-5c000e78-8d6f-46c7-ac59-218cd7ffd6c8.png">
feb9f184ee167105bd).

The current Word-based SSP template has sub-sections heading like below.<img width="789" alt="Screen Shot 2021-09-30 at 9 02 25 AM" src="https://user-images.githubusercontent.com/61464190/135460065-90ec5d88-45ba-42c5-b956-408ef0a1619c.png">

We want to match this improvements to Schematron validation outputs (SVRL) and bubble that up into the UI; we want the solution to be used in our prototype UI, but reusable for other application developers as well.

**Preconditions**
N/A

**Acceptance Criteria** 
- [ ] Updates to control-based validations' metadata to indicate sub-sections to indicate control families (AC, CM, CP, et cetera)
- [ ] An updated user interface that uses this metadata when rendering FedRAMP Word Template assertion view, as per screenshot

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by markXLIX** [comment]
This should probably be split into two stories, the validations and the UI changes.

**Comment by danielnaab** [comment]
Closing - the rules in section 13 are generally not specific to control families.
