### ISSUE TITLE
Replace the word Triggered with Flagged

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#297]
**Extended Description**
Replace the word Triggered with Flagged in the UI

**Acceptance Criteria**
- [x] Update interface with simplified wording.

**Story Tasks**
- [x] Reword `x / y triggered` for counts of validation checks applied to `x / y flagged`

**Definition of Done** - WITH UI
 - [x] Acceptance criteria met
 - [x] Unit test coverage of our code > 90% - needs automation story
 - [ ] ~Accessibility tests pass - needs automation story~
 - [x] ~Automated code quality checks pass~
 - [ ] ~Security reviewed and reported - check in with Wes on what we could do here~
 - [x] Reviewed against plain language guidelines
 - [x] Design QA passed
 - [x] Code must be self-documenting
 - [x] No local tech debt
 - [ ] ~Documentation updated~
 - [ ] ~Architectural Decision Record completed as necessary for significant design choices~
 - [x] PR reviewed & approved
 - [x] Source code merged

**Comment by rrkane10x** [comment]
@ohsh6o This story looks great. And will cover language changes in the UI.
