### ISSUE TITLE
Integrate CI/CD for Initial Schematron

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#3]
As an OSCAL user, to ensure ongoing development of validations I use in 18F/fedramp-automation#1 are actively tested, prepared, and published in a reliable way, I expect the validation developers to integrate with the existing continuous integration and continuous development pipelines in Github Actions upstream GSA developers use.

**Comment by mike-stern** [comment]
#10 enumerates additional CI/CD pipline
