### ISSUE TITLE
Rule Wording Improvements

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#301]
**Extended Description**
Swap use of "specify" with "define" in applicable assertion (not diagnostic) messages.

**Preconditions**
N/A

**Acceptance Criteria**
- [x] Swap use of "specify" with "define" in applicable assertion (not diagnostic) messages.

**Story Tasks**
- [ ] Tasks...

**Definition of Done**

**Definition of Done**
 - [x] Acceptance criteria met
 - [x] Unit test coverage of our code > 95%  
 - [x] Automated code quality checks passed 
 - [x] Security reviewed and reported (Wes to be consulted on this)
 - [x] Reviewed against plain language guidelines
 - [x] Code must be self-documenting
 - [x] No local tech debt
 - [x] Load/performance tests passed – needs to be created/automated
 - [x] Documentation updated
 - [x] Architectural Decision Record completed as necessary for significant design choices
 - [x] PR reviewed & approved
 - [x] Source code merged

**Comment by rrkane10x** [comment]
@ohsh6o Looks good with the updated global change to "specify".
