### ISSUE TITLE
Keep Transpiled Schematron Stylesheets 

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#307]
**Extended Description**
As a tool developer, in order to have easy access to the transpiled Schematron code readily available alongside the resource files and related assets.

NOTE: We already have a released artifact thanks to Dan's wonderful GitHub Actions, and we do not need or want to remove that. We just want to keep the `ssp.xsl` current in the git repo as it already is in there but 26 days old. [Open-source developers requesting that in a Gitter support thread here](https://gitter.im/compliance-trestle-IBM/community?at=61402de0d206b85e4f98c2dd).

**Preconditions**
N/A

**Acceptance Criteria**
- [ ] Determine best method to keep `ssp.sch` and `ssp.xsl` aligned during development work as merged into the `develop` branch.
- [ ] Implement method accordingly.

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by GaryGapinski** [comment]
Compilation/transpilation outputs should not be version-controlled.
