### ISSUE TITLE
Contingency Planning Checks for Periodic System Backup

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#315]
**Extended Description**
As a FedRAMP reviewer, to ensure I understand the realization of a CSP's contingency planning strategy and how they meet requirements for control CP-9, I want to know they have defined a periodic interval for information system backups.

closes #315 

**Preconditions**
- [ ] Read page 142 of [FedRAMP-SSP-Moderate-Baseline-Template](https://www.fedramp.gov/assets/resources/templates/FedRAMP-SSP-Moderate-Baseline-Template.docx) for context.

**Acceptance Criteria**
- [ ] checks implemented-requirement/statement/set-parameter values against the matching baseline-resolved-profile_catalog.xml document for matching values.  

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by markXLIX** [comment]
Link to document with pg 142 brings up a Word Doc without clear page numbering.  Thus cannot identify the context.

What are the correct intervals?

The text checks refer to CP-9 and/or other controls?

**Comment by GaryGapinski** [comment]
> Pg 142 of the referenced document refers to either CP-2.1 or CP-2.2. Neither are provide more clarity to me at least. Also neither reference CP-9 which is referenced in the Acceptance Criteria.

If one looks closely at the footer of each page in the template, the page number appears on the right. Page 142 has information about control CP-9.

![Screen Shot 2022-03-29 at 7 31 53 AM](https://user-images.githubusercontent.com/915464/160602221-a84e046e-4f7f-482c-952e-9aa0d24a2891.png)

Alternately, one can search for control CP-9 in the template regardless of page number. The table of contents also locates CP-9 on page 142.

Note the **FedRAMP Assignment** bracketed parameter expressions: these contain the desired _parameter_ choices.

> What are the correct intervals?

"[FedRAMP Assignment: daily incremental; weekly full]".

In addition to the parameter values specified in the template, the `dist/content/baselines/rev4/xml/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.xml` document can be consulted. It is too large to display on GitHub; see lines 13394-13481 (in the current `develop` branch) for additional context.

> The text checks refer to CP-9 and/or other controls?

They refer to the prose subordinate to CP-9 `implemented-requirement/statement`.

**Comment by markXLIX** [comment]
Just want to point out that the view I get when using the link to the SSP-Moderate Template shows CP-9 at page 155 in the document.  The TOC shows it at page 134.  

I understand that I could search for CP-9, of course, but I was concerned that we weren't looking at the same document due to the difference in page numbering.  I am going to assume this is a Word oddity and just move on.

**Comment by markXLIX** [comment]
Question here about the CP-9 in the template and the Acceptance Criteria about.

This statement from the template:
"Conducts backups of user-level information contained in the information system [FedRAMP Assignment: daily incremental; weekly full]" looks to indicate that 'daily full' and 'weekly incremental' would not be expected by FedRAMP. 

Should we be checking for the phrases in the template or just the individual words as shown in the AC above?

**Comment by GaryGapinski** [comment]
I (again) retrieved https://www.fedramp.gov/assets/resources/templates/FedRAMP-SSP-Moderate-Baseline-Template.docx.

There are roughly twenty pages preceding the page numbered 1. These are numbered using lower-case roman numerals. CP-9 ends up on page 142 and the ToC matches. This is using the macOS "Pages" app (the default for .docx files). AC-1 appears at numbered page 31.

Using LibreOffice on macOS, CP-9 ends up on page 133 and the ToC shows 134. The roman numeral pages are present. AC-1 appears at numbered page 26.

Using Google Docs CP-9 ends up on page 134 and the ToC matches. The roman numeral pages now are numbered beginning at 1 just after the cover page. AC-1 appears at numbered page 27.

Not particularly reliable.

**Comment by GaryGapinski** [comment]
This issue would best be handled (obviated) by completion of #153.

**Comment by GaryGapinski** [comment]
Go ahead and close this citing #153 as the general-case replacement. It would also be driven by "real data", namely the parameter setting found in the "resolved catalog" documents.

**Comment by markXLIX** [comment]
Closing in preference for #153 as a more general solution to the problem.
