### ISSUE TITLE
Add Validation for Roles and points of contact

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#32]
(Sections 3, 4, & 5) All required POCs are identified (System Owner, System ISSO, etc.)	

Simple Automation							

CSP can add POCs. Double-check to make sure all roles are listed in the Types of Users table.		

After talking with @brianrufgsa on 12/8/20, the rules are as follow:

1. Domain is simple many to many entity join: `metadata/role` M:M with `metadata/party` joined using to `metadata/responsible-party`
1. Referential Integrity Check: 
    - 	`metadata/responsible-party/@role-id` is in `metadata/role/@id`														
    - 	`metadata/responsible-party/party-uuid` is in `metadata/party/@uuid`	
1. Cardinality Check: FedRAMP specific and the role cardinality will be defined [here](https://github.com/18F/fedramp-automation/issues/32#issuecomment-740993340)
1. Roles and parties have no scope spanning outside of a document set: i.e. the baseline roles are defined for the authoring of the baseline, not as roles to be used in SSP's adhering to the baseline
1. UUID's are intended to be globally unique, but never changing for a given entity over time (there is no central store that maintains UUID & the associated entity over time, but it's an attempt to provide that).
1. UUID's may be scoped across related documents: 

> For the assessment plan and results, linking to the SSP will be unavoidable. The whole point is not to duplicate that content from the SSP into the SAP and SAR, rather to reference it back at the SSP.

**Comment by ohsh6o** [comment]
I am going to move onto another issue, but do you want to discuss pairing about this on Monday, @mike-stern?

**Comment by mike-stern** [comment]
Sounds good

**Comment by ohsh6o** [comment]
@mike-stern to further our conversation on this topic from this morning's check-in with Brian and [ongoing conversation in Gitter](https://gitter.im/usnistgov-OSCAL/FedRAMP-10x-Schematron?at=5fcfd3898cdd4340ff0ad316), we will commit an addition to the FedRAMP acceptable values in the upstream.
