### ISSUE TITLE
Check FIPS-199 Categorization Consistency with Information Types

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#322]
**Extended Description**
- As an OSCAL validation producer, in order to ensure proper SSP FIPS 199 categorization has occurred, I want to have sufficient validations to accomplish that goal.

Refer to _[Guide to OSCAL-based FedRAMP System Security Plans](https://github.com/18F/fedramp-automation/blob/develop/documents/Guide_to_OSCAL-based_FedRAMP_System_Security_Plans_(SSP).pdf)_ §4.2, §4.3, §4.4.

Refer to SSP Schematron patterns `fips-140`, `sp800-60`.

The overall FIPS 199 categorization of a system is stated in SSP `<security-sensitivity-level>`.
[FIPS 199](https://csrc.nist.gov/publications/detail/fips/199/final) describes how this is determined.

The types of information maintained within a system are specified in SSP `<system-information>` `<information-type>` elements. Each `<information-type>` has base (required) and selected (optional) security impact levels.
Information types can be found in NIST [SP 800-60 v2r1](https://csrc.nist.gov/publications/detail/sp/800-60/vol-2-rev-1/final). There is also https://github.com/18F/fedramp-automation/blob/develop/dist/content/resources/xml/information-types.xml.

NIST [SP 800-60 v1r1](https://csrc.nist.gov/publications/detail/sp/800-60/vol-1-rev-1/final) describes the categorization process. Note that the process can result in adjustments. These adjustments are noted within `<information-type>` impacts.

`<security-impact-level>` is the result of the categorization process. It's subordinate elements should be consonant with `<security-sensitivity-level>` and the (composite) `<information-type>` **selected** impacts.

In other words, the categorization process resulted in selections which are consonant with one another in these SSP areas.

**Acceptance Criteria**
- [ ] Validations exist which ensure consonance within FIPS 199 and SP 800-60 SSP elements.
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [ ] There are at least two Schematron assertions (more are quite possible depending on coding preferences) to minimally assert that
  - [ ] Every `<security-impact-level>` child element is correctly derived from the corresponding category impact set gathered from all (one or more) information types.
  - [ ] `<security-sensitivity-level>` is correctly derived from the <security-impact-level> CIA impact set.

**Story Tasks**
- [ ] Create Schematron assertions which ensure consonance within FIPS 199 and SP 800-60 SSP elements.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by GaryGapinski** [comment]
What is the question?

**Comment by jlachlan** [comment]
In any event any public data based that belong to US tax payers should be protected over the bugs of some coder trying to escalate access instead of finding solution by using math and logic not changing public resource. 

What's the motive of changing whatever your trying to do besides give your self privileged access ??

What are you trying to accomplish  and what's your bug someone can help you fix it on your end...

**Comment by markXLIX** [comment]
This is a lot of links without any specific requirements.  It is unlikely that a person outside the security domain is going to be able to create correct validations.

**Comment by GaryGapinski** [comment]
> This is a lot of links without any specific requirements. It is unlikely that a person outside the security domain is going to be able to create correct validations.

That is not a question.

**Comment by markXLIX** [comment]
> consonant

No it is not.

**Comment by GaryGapinski** [comment]
FIPS 199 describes the categorization process in a more concise way (compared to SP 800-60), but from an OSCAL aspect the (1 or more) information types (`<information-type>`) each have confidentiality, integrity, and availability impacts. Each impact has a required base value and optional selected value. The highest (low < moderate < high) impact of all the respective confidentiality, integrity, and availability base and selected values determines the respective values of `<security-impact-level>` respective child elements. The validation should affirm that is the case. Additionally, the badly-named `<security-sensitivity-level>` (FIPS 199 categorization) should be the highest (low < moderate < high) impact of the `<security-impact-level>` child elements.

One Schematron assertion message could be "The security impact levels are consonant with the information types."
Another Schematron assertion message could be "The security sensitivity level is consonant with the security impact levels."
