### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by GaryGapinski** [18F/fedramp-automation#394]
Extended Description**
- As an OSCAL developer, in order to ensure common XML formatting techniques, I want to have the formatting parameters defined.

**Acceptance Criteria**
- Updated `CONTRIBUTING.md`.

**Story Tasks**
- [x] Update `CONTRIBUTING.md` removing obsolete reference to HTML Tidy and replace with OxygenXML Editor related settings.

**Definition of Done**
 - [x] Acceptance criteria met
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by markXLIX** [comment]
While you are in there could you provide some more detail on the Pull request titles?  Perhaps a real world example to go with the generic one?  Or a link to the exact location for the 'Angular Coding Conventions'?
