### ISSUE TITLE
FedRAMP Automation documentation updates

### ISSUE THREAD

**Issue by GaryGapinski** [18F/fedramp-automation#399]
Extended Description**
- As a 10x ASAP developer, in order to update fedramp-automation documentation, I want to find out how to do so.

**Preconditions**
- Preconditions...

**Acceptance Criteria**
- A demonstration that FedRAMP automation documentation can be updated.

**Story Tasks**
- [ ] Determine how documentation updates are performed.
- [ ] Perform an update.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported (Wes to be consulted on this)
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by jlachlan** [comment]
Was this the last comment, No FedRamp is not controlled by the seed fund for children !

**Comment by jlachlan** [comment]
Code self document is log4j bs or forcing comments triggered at false events to collect data.

FedRamp is already giving you millions of hours of free IP and labor and your complaining bc your can update a word doc? 

Use MS office, update fields from index to bookmarks in word or use excel dynamic links 

Upload word doc saved as html 

What is the purpose of you knowing how the security works and what was changed besides attacking the changes like this request for privilege are you impersonating a federal official too ?

**Comment by jlachlan** [comment]
If you can automate a text based protocol your running code in the browser by definition !

**Comment by GaryGapinski** [comment]
This is now being handled by FedRAMP using https://github.com/GSA/fedramp-automation-guides (and separate upstream documents).
