### ISSUE TITLE
Release Compiled XSLT Versions of Validations

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#47]
As a tool author, to expedite integration of the rules and their framework into our code, I would like the compiled rules and framework without having to compile them from repo source code.

**Extended Description**

Currently, any external developer will need 

**Preconditions**
- [x] Make this part of release strategy: 18F/fedramp-automation#53.
- [x] Reorganize source code to make this easier to handle: 18F/fedramp-automation#131

**Acceptance Criteria**
- [x] A Github Action that will be compile release builds of XSLT and FedRAMP values for customers.
- [x] Documentation on how to prep and promote a compiled release at end of sprint for release.
- [x] Documentation on how to move 18F branch releases upstream into GSA/fedramp-automation upstream repo for final official releases
- [x] Release of the first release of course! :-P

**Story Tasks**
- [x] Add Makefile to streamline build and deploy processes
  - [x] `init` task to install deps (`git submodule` in `./vendor`)
  - [x] `clean` the repo.
   - [x]  `all` build everything, i.e.:
   - [x] `build-web` to build the website
   - [x] `build-validation` to build the validation rules from Schematron to XSLT (Java variant for now)?
  - [x] `test` to execute all the test suites
    - [x] `test-web` to execute web suite
   - [x] `test-validations` to execute the validation suite

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [x] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [x] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [x] Source code merged - Code that’s demoed must be in source control and merged
 - [x] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [x] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [x] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [x] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [x] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [x] Code refactored for clarity - Code must be clean, self-documenting
 - [x] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [x] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by mike-stern** [comment]
Blocked by #53

**Comment by GaryGapinski** [comment]
Since we have used XSLT 3.0 and XPath 3.1, compiled (into XSLT) validations will require an XSLT 3.0 and XPath 3.1 execution environment.

**Comment by ohsh6o** [comment]
@danielnaab we are still on target for release around 12 August 2021 I think on the FR side. No pressure on you, but can we ensure you test this upstream and we target before a _pre-release_ (this is a check box in Github) and call your test release in GSA/fedramp-automation `fedramp1.1.0pre-oscal1.0.0`?

**Comment by danielnaab** [comment]
Alpha release in GSA/fedramp-automation - https://github.com/GSA/fedramp-automation/releases/tag/fedramp1.1.0-oscal1.0.0-alpha
