### ISSUE TITLE
Create FedRAMP OSCAL content for SP 800-53 rev5

### ISSUE THREAD

**Issue by delnaweil** [18F/fedramp-automation#478]
**Extended Description**
- As a FedRAMP PMO manager, in order to accommodate the fifth revision of NIST SP 800-53, I want OSCAL content created analogous to that created for the fourth revision of NIST SP 800-53.

**Preconditions**
- [ ] Determine if FedRAMP has already manufactured OSCAL content for rev5.
- [ ] Familiarity with [NIST SP 800-53 version 5](https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final).
- [ ] Familiarity with [NIST SP 800-53B](https://csrc.nist.gov/publications/detail/sp/800-53b/final) (there was no version 4).
- [ ] Familiarity with [NIST SP 800-53A version 5](https://csrc.nist.gov/publications/detail/sp/800-53a/rev-5/final).
- [ ] Familiarity with [NIST OSCAL Content](https://github.com/usnistgov/oscal-content/tree/v1.0.0), particularly [rev5](https://github.com/usnistgov/oscal-content/tree/v1.0.0/nist.gov/SP800-53/rev5/xml).
- [ ] Familiarity with [FedRAMP OSCAL rev 4 Content](https://github.com/18F/fedramp-automation/tree/master/dist/content).
- [ ] Familiarity with NIST [OSCAL _Catalog_ and _Profile_](https://pages.nist.gov/OSCAL/concepts/layer/control/) concepts.
- [ ] Familiarity with [NIST OSCAL Profile Resolution Specification](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/).
- [ ] Familiarity with [SP 800-53 OSCAL comparison](https://github.com/GaryGapinski/oscal-compare), particularly the [rev4 to rev5 ODP mapping](https://github.com/GaryGapinski/oscal-compare/blob/main/odp-mapping.xml).
- [ ] Familiarity with [NIST OSCAL XML to JSON Converters](https://github.com/usnistgov/OSCAL/tree/main/json/convert).

**Acceptance Criteria**
- [ ] Story tasks are complete.

**Story Tasks**
- [ ] Create an OSCAL XML `catalog` via one or more XSLT transforms using input from [NIST OSCAL SP 800-53 rev5 content](https://github.com/usnistgov/oscal-content/tree/v1.0.0/nist.gov/SP800-53/rev5/xml).
- [ ] Create one OSCAL XML `profile` via one or more XSLT transforms for each SP 800-53B Low, Moderate, and High baseline using input from **v1.0.0** [NIST OSCAL SP 800-53 rev5 content](https://github.com/usnistgov/oscal-content/tree/v1.0.0/nist.gov/SP800-53/rev5/xml), corresponding [FedRAMP OSCAL rev4 profiles ](https://github.com/18F/fedramp-automation/tree/master/dist/content/baselines/rev4/xml), and the [rev4 to rev5 ODP mapping](https://github.com/GaryGapinski/oscal-compare/blob/main/odp-mapping.xml). Map FedRAMP rev4 profile customization artifacts to the corresponding rev5 profile customization artifacts. Prepare a composite list of novel (rev5) ODPs for FedRAMP to identify any FedRAMP-desired constraints.
- [ ] Create OSCAL XML "resolved profile catalog" `catalog` documents for each baseline using the OSCAL profile resolution transform(s).

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by GaryGapinski** [comment]
Waiting for confirmation from FedRAMP PMO.

**Comment by GaryGapinski** [comment]
See branch [issue-478](https://github.com/18F/fedramp-automation/tree/issue-478).

**Comment by delnaweil** [comment]
FedRAMP is handling independently
