### ISSUE TITLE
Schematron performance profiling

### ISSUE THREAD

**Issue by GaryGapinski** [18F/fedramp-automation#502]
**Extended Description**
Profile Schematron validations against full (i.e., output of `sample-ssp.xsl`) SSP instance document.

**Acceptance Criteria**
- [x] Serious hotspots are corrected/refactored/improved.

**Story Tasks**
- [x] Read https://www.oxygenxml.com/doc/versions/24.1/ug-editor/topics/performance-profiling.html.
- [x] Profile transpiled `ssp.sch` Schematron.
- [x] Correct/refactor/improve serious hotspots.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by GaryGapinski** [comment]
Hot spots seem to be associated with XSLT-oriented validations. Requires #503.

**Comment by danielnaab** [comment]
Remaining issues are due to SaxonJS inefficiencies
