### ISSUE TITLE
Schematron rule presentation improvements

### ISSUE THREAD

**Issue by danielnaab** [18F/fedramp-automation#551]
**Extended Description**
As a user, I would like to have clarity in understanding the meaning of various assertions, their relative importance, and their pass and fail status.

**Acceptance Criteria**
- [ ] User feedback from phase 3 sessions addressed

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by fpigeonjr** [comment]
closed via[ PR557](https://github.com/18F/fedramp-automation/pull/557)
