### ISSUE TITLE
Bug: evaluation of sample POA&M fails

### ISSUE THREAD

**Issue by danielnaab** [18F/fedramp-automation#579]
Validation of the sample POA&M document via SaxonJS produces this error:

```
Required cardinality of second argument of map:get() is exactly one; supplied value is empty
```

This is triggered on this line of the compiled `poam.xsl`:

```
      <xsl:variable name="no-later-than" select="xs:dateTime($detected) + map:get($threshold, $impact)"/>
```

Which was introduced with this commit: https://github.com/18F/fedramp-automation/commit/bda0a4071f48504094c6cf467f2d44c18a3750bc

**Comment by GaryGapinski** [comment]
@danielnaab : I think this was corrected in 0ccb4409a093ce1cfb3faa7b9477462ec2822621 but I can't find the related PR. The git history does show that commit 2022-07-01.
