### ISSUE TITLE
As a Product Owner I want the voice of the customer represented in the priority and review of the team's output so that the delivered product meets their needs.

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#66]
Acceptance Criteria: 
- [x] Review with Product Owner existing documentation and user guidance
- [x] Begin planning review process with Melissa Avalos and Bridget Dorward?
- [x] Introduction to Michaela from NIST
- [ ] Other opportunities for UX representation

**Comment by ohsh6o** [comment]
@rrkane10x and I are beginning work on briefing and strategizing user research with FedRAMP Agency Review Team with these documents:

- [Briefing notes](https://docs.google.com/document/d/1hsoMaXoObQnn7y2WFWy6bdBJQdotlzEcGZjmIYS0IeU/edit)
- [Finalized kickoff presentation](https://docs.google.com/presentation/d/1xKFqvxTIfj8TqL7uFFzjTuzJJOXPVaD5T_QnMdww9_U/edit?ts=60998a93#slide=id.g875b4e9dce_0_1176)

Intent is to brief and meet the Agency Review Team and begin taking next steps before Sprint 1 wraps up.

**Comment by ohsh6o** [comment]
Setting up a meeting with Michaela to discuss the NIST perspective on OSCAL. Also began providing more FedRAMP documentation relevant to overall process and UX impact in the P3 folder after getting permission from the FedRAMP PMO.

https://drive.google.com/drive/folders/1DgEYjP_hqQiWbbH8PFei-Bw3UtOX9ePB

**Comment by ohsh6o** [comment]
@rrkane10x and I had a chance to present for the kickoff and we will need to work through some next steps with the FedRAMP PMO and Agency Review Team for next steps.

- [ ] FART members will provide a copy of updated checklist documentation for potentially ABD, DFD, and potentially overall package review (that is more recent than [the PDF version of the Excel spreadsheet checklist we have been operating on](https://www.fedramp.gov/assets/resources/templates/FedRAMP_Agency_Authorization_Review_Report_Sample_Template.pdf).
- [ ] FedAMP PMO (Melissa) will schedule user feedback sessions with FART members based on the timeline in the linked presentation.
- [ ] FART agreed to investigate bringing Robin and I into FART review meetings after NDA signed. AJ will work with Zach to get NDA signed and begin collaboration on that.
- [ ] AJ (on behalf of FedRAMP PMO) and Robin will meet tomorrow on next steps on planning future UX work given the feedback and proposed timeline in this meeting to prep for the next and future backlog refinements.

**Comment by ohsh6o** [comment]
Also, per backlog review with Mike today and the last point above, prepare with a placeholder item in GSA/fedramp-automation#80, and get it shovel ready for next sprint if possible.

**Comment by ohsh6o** [comment]
FedRAMP PMO also communicated their recommendation we include FerRAMP Joint Authorization Board (JAB) Technical Reviewers in feedback for validation outputs and future UX/UI efforts as they evolve. Melissa in the FedRAMP PMO will be in touch with future details.

**Comment by ohsh6o** [comment]
Robin and I met Friday to discuss next steps, and met with Michaela earlier this morning. We agreed that 18F/fedramp-automation#80 is the best next step forward for UX work for now, and not get too into the weeds this early on. Robin will need some time to digest and further orient herself after material review, initial kickoff meetings, and impromptu pre-planning sessions.

We agreed future planning on UX collaboration with Michaela and NIST could be fruitful, but will have to wait for now. I will send a thank you email to Michaela and ask about one related project around building a desktop application/client processing that was part of a government research grant and potential UX insights, but it is likely that Michaela has limited details and cannot provide more detail at this time.

**Comment by ohsh6o** [comment]
As we have taken it pretty far, I think I will mark this one ready for review. @mike-stern, thoughts? For a story/tasking like this, do we need to follow a team's DoD. The acceptance criteria are somewhat vague, but this issue was largely necessary prep work, but I want to follow team process and standards. Let me know!
