### ISSUE TITLE
Review ConOp for FedRAMP process

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#67]
AJ will present to the team the conop doc from the volpes

**Comment by ohsh6o** [comment]
We reviewed the ConOps document as a group and determined it is best we meet with VGIT to discuss the following issues:

- Can the GSA OSCAL Generation Tool produce the OSCAL format SSP and then we analyze that to understand thee mapping output?
- Do they 100% conformal mapping from their data model to the OSCAL data model?
- If we can generate a unique identifier for every Schematron assertion, will that be sufficient for the OSCAL Generation Tool to map from the OSCAL XML data model <-> app data model <-> Microsoft Word data model (if different from the former)?
- Do we need or want a "regular pattern" for Schematron validations and must we expand into grammar in a way that is useful to integrating software like this tool?

**Comment by ohsh6o** [comment]
Email sent, will set up a kick-off meeting, plan next steps, and move this meeting to ready for review.

**Comment by ohsh6o** [comment]
Will discuss what should be done to wrap this up hopefully in standup coming up shortly.
