### ISSUE TITLE
As a FedRAMP developer and downstream consumer, to understand re-usability of the validation software and  additional fedramp-automation material in the repo, I want the FedRAMP PMO to determine a license for the source code repository.

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#69]

**Comment by ohsh6o** [comment]
This is on hold until we hear back from Zach.

**Comment by mike-stern** [comment]
Need to check flexion's BPA or cede company rights if this is going to be stamped CC

**Comment by ohsh6o** [comment]
Will close this for the sprint and continue to track upstream as a FedRAMP PMO concern in GSA/fedramp-automation#87.
