### ISSUE TITLE
Prepare Allowed Values from OSCAL and FedRAMP Before Runtime

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#71]
As a developer using the FedRAMP Validations, in order to read important values needed for validation *at build time* without needing to change or understand the validations' source code , I want the FedRAMP Validations to process values from OSCAL source code and FedRAMP values on the fly.

**Context:**

This is the spike to research the viability of `o:allowed-values` from multiple sources: investigate programmatically generating Schematron from OSCAL Metaschema and FedRAMP extensions

**Pre-conditions:**

**Acceptance Criteria:**
- [ ] understand how their future vision of OSCAL metaschema and FedRAMP extensions may enable 
- [ ] Update mechanism for reading FedRAMP Extension data for o:allowed-values
- [ ] Document strategy for handling OSCAL Metaschema data for o:allowed-values that will need to be used to match
- [ ] Update mechanism for reading OSCAL Metaschema data for o:allowed-values

**Definition of Done:**

**Comment by sstatz** [comment]
Wait for review.  Needs more discussion.

**Comment by sstatz** [comment]
Need to coordinate with NIST OSCAL developers.
