### ISSUE TITLE
SSP element Href Attribute Error Generation During POAM Ingest - Causing Validator issue

### ISSUE THREAD

**Issue by Telos-sa** [18F/fedramp-automation#726]
# Describe the bug

Errors seem to be ad odds with each other.  

![image](https://user-images.githubusercontent.com/127163717/224851195-a3ecca90-44e9-4592-a5e4-31433828cbf9.png)

Have an SSP, and referenced the ssp uuid to generate the link.  The SSP is included in the backmatter, with the relational reference to its location.  

When you click on the "View Examples" options of the two fatal errors, they load to a white screen that seems to escape the validator.  The only way to navigate back is to recycle the page, having to start all over again.  

# Who is the bug affecting?
Have tried different SSP import references, and these errors continue to persist.  

# What is affected by this bug?
https://federalist-2372d2fd-fc94-42fe-bcc7-a8af4f664a51.sites.pages.cloud.gov/site/18f/fedramp-automation/#/documents/plan-of-action-and-milestones

{Describe the impact the bug is having.}

# When does this occur?
When clicking on the view examples of the validator of the fatal errors.  

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}
Test with attached generated POAM file, and it will produce the same result.  

{If applicable, add screenshots to help explain your problem.}
[FedRAMP 03062023 FedRAMP Plan of Action and Milestones.json.zip](https://github.com/18F/fedramp-automation/files/10962583/FedRAMP.03062023.FedRAMP.Plan.of.Action.and.Milestones.json.zip)

# Other Comments

Please give examples as to why this is a fatal error, and best way to avoid it.  Want to reduce / remove any schema issues

**Comment by danielnaab** [comment]
This fork is currently inactive and will be archived soon. The upstream - https://github.com/GSA/fedramp-automation - is where all future development is taking place. The most recent Cloud.gov Pages deployment for that branch is available here:

https://federalist-b6c4d61f-facd-4833-a4a9-554523a87147.sites.pages.cloud.gov/site/gsa/fedramp-automation/#/rev4/documents/plan-of-action-and-milestones

**Comment by Telos-sa** [comment]
Does that mean that I should create a new bug?

**Comment by danielnaab** [comment]
> Does that mean that I should create a new bug?

Thanks, closing in favor of https://github.com/GSA/fedramp-automation/issues/395
