### ISSUE TITLE
As a SSP creator, I would like more flexibility in running validations, to accommodate for my runtime environment.

### ISSUE THREAD

**Issue by mike-stern** [18F/fedramp-automation#9]
A couple enhancements for bin/validate_with_schematron.sh

- [ ] utilize SAXON_HOME similar to how xspec handles it
- [ ] add command line options (rather than positional arguments)
- [ ] add report options (make HTML optional via switch)
- [ ] add folder support for documents in rather than a single document

**Comment by ohsh6o** [comment]
Per conversation with @mike-stern, this had been completed a while ago during 10x ASAP P2 development cycle.
