### ISSUE TITLE
Verify Validations Work for NIST v1.0.0 OSCAL Release

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#90]
As a 10x or third-party developer, in order to ensure the FedRAMP Validations are ready for use with the most current production release, I want the validations reviewed for correctness in connection with the current stable release.

**Extended Description**

Per 18F/fedramp-automation#81, the NIST OSCAL 1.0.0 release was pushed back to the middle of this week and/or next week.

**Preconditions**
- [x] Official published OSCAL 1.0.0 release.

**Acceptance Critera**
- [ ] Completed review document
- [x] A PR to change our Schematron rules, as appropriate

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by ohsh6o** [comment]
FYI/FYE, OSCAL 1.0.0 was [released last night](https://pages.nist.gov/OSCAL/reference/release-notes/#oscal-100-release).

CC @danielnaab and @GaryGapinski

**Comment by ohsh6o** [comment]
FYI/FYE [FedRAMP 1.0.0 for OSCAL 1.0.0](https://github.com/GSA/fedramp-automation/releases/tag/fedramp1.0.0-oscal1.0.0) was released last night.

**Comment by ohsh6o** [comment]
I linked the relevant issue, 18F/fedramp-automation#117. Can one or both of you (@danielnaab or @GaryGapinski) check this is ready to go tomorrow morning before sprint closeout?

**Comment by GaryGapinski** [comment]
Closed by #129.
